- title: Занятие 3
- author: Ivan Stepanov
- date: 2023-10-27
- slug: s3_lab03
- ipynb_url: download/s3_lab03.ipynb

# Лабораторная работа 3

***NumPy***(сокращенно от Numerical Python)— библиотека с открытым исходным кодом для языка программирования Python.

* поддержмвает многомерные массивы (включая матрицы)
* поддерживает высокоуровневые математические функции, предназначенные для работы с многомерными массивами.

NumPy обеспечивает как гибкость Python, так и скорость хорошо оптимизированного скомпилированного кода на C. 

Если у вас ещё не установлен Numpy это можно сделать командой: pip install numpy

##  0. Массивы в Numpy 

* Массив в NumPy это таблица элементов одного типа, пронумерованная кортежем положительных целых чисел.
* В NumPy измерения называются осями. Количество осей является рангом.
* Класс массива NumPy называется ndarray.

Обратите внимание, что массив в Numpy содержит элементы одного типа, в отличие от списка!

In [1]:
import numpy as np # импортируем библиотеку и заменим её ключевым словом np(для удобства)

In [2]:
arr1 = np.array([1, 2, 3]) # массив ранга 1
arr2 = np.array( [[1, 2, 3], [4, 2, 5]] ) # массив ранга 2(матрица с двумя строками и тремя столбцами)

## 1. Создание массива

Есть несколько способов создать массив NumPy. Рассмотрим их подробнее:   

### 1.1 Функция array

Вы можете создать массив из обычного списка или кортежа, используя array().

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype = 'int')
print(a)

[[1 2 3]
 [4 5 6]]


### 1.2. Создание массива заполнением начальными значениями

Допустим нам неизвестны элементы массива, но известен его размер. В NumPy существуют функции для создания массивов с начальным заполнением. 

In [ ]:
a = np.zeros(5) # создаём 1-d массив, содержащий 5 нулей
print('a:', a)
b = np.zeros((2, 3)) # создаём 2-d массив, размера 2 на 3
print('b:', b)
r = np.random.random(5) # создаём массив со случайными значениями на определённом интервале
print('r:', r)

a: [0. 0. 0. 0. 0.]
b: [[0. 0. 0.]
 [0. 0. 0.]]
r: [0.48573418 0.73455963 0.79920779 0.07569678 0.8825991 ]


### 1.3. Фунция arange

In [5]:
a = np.arange(0, 10, 2) # создаём массив от 0 до 10 с шагом 2
print(a)

[0 2 4 6 8]


### 1.4. reshape

Мы также можем менять размеры массивов. Размер массива всегда можно вычислить командой a.shape

In [6]:
a = np.array([[1, 2, 3, 4], [5, 2, 4, 2]])
print('a: ', a.shape)
new_a = a.reshape(4, 2)
print('new_a: ', new_a.shape)

a:  (2, 4)
new_a:  (4, 2)


### 1.5. flatten

Любой многомерный массив мы можем развернуть с помощью функции flatten.

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 2, 4, 2]])
new_a = a.flatten()
print(new_a)

[1 2 3 4 5 2 4 2]


## 2. Идексация массивов

### 2.1 Одномерных

In [ ]:
a = np.arange(10) # создадим массив
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# как можно заменить доступ остался таким же как в списках
print('четвёртый элемент:', a[3])
print('последний элемент:', a[-1])
a[3] = 11
print('теперь четвёртый элемент:', a[3])

четвёртый элемент: 3
последний элемент: 9
теперь четвёртый элемент: 11


In [ ]:
# мы также можем создавать срезы, как и в списках.
new_a = a[1:5]

In [ ]:
# теперь немного магии
new_a[1] = -10
print(a)

[  0   1 -10  11   4   5   6   7   8   9]


Мы поменяли элемент среза и наш исходный массив тоже изменился!!! Почему?  Это сделано специально для экономии памяти. Данные на которые ссылаются ***a*** и ***new_a*** одни и те же. Срезы – это не полноценные копии массивов, а скорее их новое представление.

### 2.2 Многомерных

In [7]:
x = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)]) # создаём многомерный массив

С точки зрения математики, можно сказать, что нашим объектом является следующая матрица. 

\begin{equation}
  \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6\\
    7 & 8 & 9
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}

In [ ]:
#мы также можем обращаться к элементам матрицы следующим образом
print(x[2][2])
# можем обратиться только к конкретной строке 
print(x[0])
# к конкретному столбцу
print(x[:,0])

9
[1 2 3]
[1 4 7]


Итерирование многомерных массивов можно выполнять с помощью вложенных циклов. 

In [ ]:
for row in x:
    for value in row:
        print(value, end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


Можно использовать flat, позволяющий выводить элементы многомерного массива поэлемента. 

In [ ]:
for val in x.flat:
    print(val, end=' ')

1 2 3 4 5 6 7 8 9 

## 3. Операции над массивами

### 3.1 Математические операции

In [ ]:
# создадим два массива
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
b = np.array([(19, 20, 21), (22, 23, 24), (25, 26, 27)])

Мы можем складывать, умножать, делить, считать остаток и т.д поэлементно.

In [ ]:
# сумма
print(a + b)

[[20 22 24]
 [26 28 30]
 [32 34 36]]


In [ ]:
# разность
print(a - b)

[[-18 -18 -18]
 [-18 -18 -18]
 [-18 -18 -18]]


In [ ]:
# умножение
print(a * b)

[[ 19  40  63]
 [ 88 115 144]
 [175 208 243]]


In [ ]:
# остаток от деления
print(b % a)

[[0 0 0]
 [2 3 0]
 [4 2 0]]


In [ ]:
# Также, в numpy есть библиотека стандартных мат функций, которые можно применить к каждому элементу массива. 
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 3.2 Базовые операции с массивыми

In [ ]:
a = np.array([(1, 2, 3, 4, 5, 6, 7, 8, 9)])
# сумма элементов
print(a.sum())
# произведение элементов
print(a.prod())
# макс и мин элемент
print(a.max())
print(a.min())
# среднее значение
print(a.mean())
# дисперсия
print(a.var())

45
362880
9
1
5.0
6.666666666666667


***P.S NumPy - мощный интсрумент, который содержит в себе много функций и методов.*** 

Обращайтесь к туториалу: https://numpy.org/devdocs/user/quickstart.html

И не бойтесь гуглить!

### Задача 1

Создайте две numpy матрицы, содержащие температуры в Кельвинах и Фаренгейтах на основе матрицы температур в Цельсиях.

In [7]:
a = np.array([(14, 23, 31, 14, 55, 36, 87, 118, 91)]) # матрица температур(в Цельсиях)

In [11]:
np.vectorize(lambda x: x + 273)(a)

array([[287, 296, 304, 287, 328, 309, 360, 391, 364]])

In [12]:
np.vectorize(lambda x: x * 100 / 36.6)(a)

array([[ 38.25136612,  62.84153005,  84.69945355,  38.25136612,
        150.27322404,  98.36065574, 237.70491803, 322.40437158,
        248.63387978]])

### Задача 2
Создайте матрицу с 0 внутри и 1 на границах.

In [16]:
n, m = 5, 5
ans = [[1] + [0] * (m - 2) + [1] if 0 < i < n - 1 else [1] * m for i in range(n)]
np.array(ans)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### 3.3 Умножения матриц

In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
a = np.array([(1), (4), (7)])
# можем так
print(a @ b)
# а можем так
print(a.dot(b))

[282 294 306]
[282 294 306]


### Задача 3 

Посчитайте произведение матриц используя:
* @
* dot
* не используя ни dot, ни @

In [17]:
A = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])
B = np.array([[11.0, 12.0],
              [13.0, 14.0],
              [15.0, 16.0]])

In [19]:
A @ B

array([[ 82.,  88.],
       [199., 214.]])

In [ ]:
A.dot(B)

In [26]:
C = [[0] * A.shape[0] for _ in range(B.shape[1])]
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for r in range(A.shape[1]):
            C[i][j] += A[i][r] * B[r][j]
np.array(C)

array([[ 82.,  88.],
       [199., 214.]])

### Задача 4

Мы можем расчитать норму вектора: ***np.linalg.norm([1.0, 2.0, 3.0])***.

Найдите косинус угла между векторами:
* используя np.linalg.norm
* не используя



In [28]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])

In [33]:
np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)

0.9746318461970762

In [34]:
linalg = lambda x: np.sqrt(sum((i ** 2 for i in x)))
np.dot(a, b) / linalg(a) / linalg(b)

0.9746318461970762

## 4. Линейнай алгебра в NumPy


### 4.1 Решение систем линейных уравнений

Библиотеку numpy удобно использовать для решения систем линейных уравнений. Если система уравнений $Ax = y$ имеет решение, и при этом только одно, то оно выражается как $x = A^{-1}y$ . Для обращения матрицы используется функция np.linalg.inv. Рассмотрим систему уравнений:
$$
\left\{ 
\begin{array}{c}
2x + z = 1 \\ 
x - z = 4 \\ 
\end{array}
\right. 
$$

In [35]:
A = np.array([[2.0, 1.0],
              [1.0, -1.0]])
y = np.array([1.0, 4.0])
# решение будет
print(np.linalg.inv(A) @ y)

[ 1.66666667 -2.33333333]


### Задача 5

Решите следующую систему:

$$
\left\{ 
\begin{array}{c}
2x+3y+4z = 5 \\ 
x-y+z=3 \\ 
2x+6y-3z=4
\end{array}
\right. 
$$

In [8]:
A = np.array([[2.0, 3.0, 4.0],
              [1.0, -1.0, 1.0],
              [2.0, 6.0, -3.0]])
y = np.array([5.0, 3.0, 4.0])
# решение будет
print(np.linalg.inv(A) @ y)

[ 2.73170732 -0.2195122   0.04878049]


### 4.2 Ещё немного линейной алгебры

### Задача 6

Дана матрица B.

Найдите её:

* детерминант
* ранг
* собственные значения

P.S воспользуйтесь полезным туториалом: https://www.geeksforgeeks.org/numpy-linear-algebra/?ref=lbp.

In [12]:
B = np.array([[11.0, 12.0],
              [13.0, 14.0],
              [15.0, 16.0]])

In [13]:
np.linalg.det(B)

LinAlgError: Last 2 dimensions of the array must be square

In [10]:
np.linalg.matrix_rank(B)

2

In [14]:
np.linalg.eig(B)

LinAlgError: Last 2 dimensions of the array must be square

## 5. Математика многочленов

### 5.1 np.poly

In [ ]:
# np.poly - передаём список корней, получаем коэффициенты уравнения, которое имеет данные корни:
np.poly([-1, 1, 2])

array([ 1., -2., -1.,  2.])

Получили уравнение:

$x^3 -2x^2 -x + 2 =0$

### 5.2 roots

In [ ]:
# np.roots - передаём список коэффициентов уравнения, возвращаем корни.
np.roots([1, -5, 6])

array([3., 2.])

Мы решили уравнение: $x^2 - 5x + 6 = 0$

### Задача 7

Напишите функцию решающую квадратное уравнение и принимающую на вход коэффициенты этого уравнения.

In [16]:
np.roots(list(map(float, input().split())))

array([3., 2.])

### Задача 8

Теперь решите задачу 7, не используя np.roots.

Почувствуйте разницу)

In [ ]:
import math
 
print("Введите коэффициенты для уравнения")
print("ax^2 + bx + c = 0:")
a = float(input("a = "))
b = float(input("b = "))
c = float(input("c = "))
 
discr = b ** 2 - 4 * a * c
print("Дискриминант D = %.2f" % discr)
 
if discr > 0:
    x1 = (-b + math.sqrt(discr)) / (2 * a)
    x2 = (-b - math.sqrt(discr)) / (2 * a)
    print("x1 = %.2f \nx2 = %.2f" % (x1, x2))
elif discr == 0:
    x = -b / (2 * a)
    print("x = %.2f" % x)
else:
    print("Корней нет")

## 6. Разные задачки

P.S При решении рекомендуется обращаться к руководству пользователя NumPy: https://numpy.org/doc/stable/user/index.html

### Задача 9

Дан массив a. Поменяйте знак у элементов, кратных трём.

In [ ]:
a = np.arange(20)

### Задача 10

Дано 4 точки у каждой из которых есть координата x и y. Значения x и y каждой точки представлены в матрице A.

Преобразуйте их в полярные координаты.

In [ ]:
A = np.array([[1,1],[1,0], [0,1], [0,0]]).astype(float)

### Задача 11

Напишите функцию, которая определяет есть ли в 2D массиве нулевые столбцы.

### Задача 12

Найдите наиболее частое значение в массиве.

### Задача 13

Найдите наиболее частое значение в массиве.

### Задача 14(2 балла)

Создайте класс Matrix, добавьте в него методы сложения, умножения, транспонирования, возведения в степень.

### Задача 15

Пусть дано n, матрица A. Напишите функцию, вычисляющую ряд: $A + A^2 + ... A^n$.